site_name: Test docs
site_description: 'A docs test'
site_author: 'Zoltan Hrabovszki'
docs_dir: docs/
repo_name: 'hrabovszki1023/HarmonyDocs'
repo_url: 'https://github.com/Hrabovszki1023/HarmonyDocs'
nav:
    - Home: 'index.md'
    - 'OKW':
        - 'keywordslist'
        - 'SetValue': 'SetValue'
    - About: 'about.md'
theme:
  name: 'material'
